# Generated by Django 3.1.7 on 2021-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveis', '0003_auto_20210311_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movel',
            name='categoria',
            field=models.CharField(choices=[('RE', 'Residencial'), ('CO', 'Corporativo'), ('EC', 'Escritório'), ('HO', 'Home Office'), ('ES', 'Estudante')], max_length=2, verbose_name='Situação'),
        ),
    ]
